apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: test-sliit
  name: test-sliit
spec:
  ports:
    - port: 3002
      protocol: TCP
      targetPort: 3002
  selector:
    app: test-sliit
status:
  loadBalancer: {}